<?php

namespace Controller;

use View\View;

class NewAdController extends CarController
{
    protected  $tableName = "car";

    public function __construct(View $view)
    {
        parent::__construct($view);
        $this->view->setFolder('newAdvertisement');
    }

    public function actionShow(array $data)
    {
        parent::actionShow($data); // TODO: Change the autogenerated stub
        $this->view->addData(['userId'=>$_SESSION['user']['id']]);
    }

    public function actionAdd(array $data)
    {
        $error = false;

        if (empty($data['post']['name_of_car'])) {
            $_SESSION['errors'][] = 'Надо задать имя автомобиля';
            $error = true;
        }

        if (empty($data['post']['year_of_issue'])) {
            $_SESSION['errors'][] = 'Надо задать год автомобиля';
            $error = true;
        }

        if (empty($data['post']['condition_car'])) {
            $_SESSION['errors'][] = 'Надо задать год автомобиля';
            $error = true;
        }

        if (empty($data['post']['mileage'])) {
            $_SESSION['errors'][] = 'Надо задать год автомобиля';
            $error = true;
        }

        if (empty($data['post']['fuel_type'])) {
            $_SESSION['errors'][] = 'Надо задать год автомобиля';
            $error = true;
        }

        if (empty($data['post']['volume'])) {
            $_SESSION['errors'][] = 'Надо задать год автомобиля';
            $error = true;
        }

        if (empty($data['post']['color'])) {
            $_SESSION['errors'][] = 'Надо задать год автомобиля';
            $error = true;
        }

        if (empty($data['post']['body_type'])) {
            $_SESSION['errors'][] = 'Надо задать год автомобиля';
            $error = true;
        }

        if (empty($data['post']['transmission'])) {
            $_SESSION['errors'][] = 'Надо задать год автомобиля';
            $error = true;
        }

        if (empty($data['post']['drive_unit'])) {
            $_SESSION['errors'][] = 'Надо задать год автомобиля';
            $error = true;
        }

        if (empty($data['post']['price'])) {
            $_SESSION['errors'][] = 'Надо задать год автомобиля';
            $error = true;
        }

        if (!$error) {
            $data['post']['image'] = $_FILES['image']['name'];
            $ext = pathinfo($_FILES['image']['name'], PATHINFO_EXTENSION);
            $id = $this->table->add($data['post']);
            move_uploaded_file($_FILES['image']['tmp_name'], "images/products/$id.$ext");
            $this->redirect('?action=show&type=usercar');
        } else {
            $_SESSION['addData'] = $data['post'];
            $this->redirect('?action=show&type=newad');
        }
    }
}
